---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: deployment.yaml
  - target:
      kind: GRPCRoute
      name: person-service-route
    patch: |-
      - op: add
        path: /spec/rules/0/matches/0/headers
        value: []
      - op: add
        path: /spec/rules/0/matches/0/headers/-
        value:
          name: x-subdomain
          type: Exact
          value: sandbox
      - op: add
        path: /spec/rules/-
        value:
          backendRefs:
            - name: person-service
              port: 50051
              group: ''
              kind: Service
              weight: 1
          matches:
            - path:
                type: PathPrefix
                value: /
  - target:
      kind: Service
      name: person-service
    patch: |-
      - op: add
        path: /spec/selector/environment
        value: sandbox
