apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: production
  name: person-service
spec:
  selector:
    matchLabels:
      environment: production
  template:
    metadata:
      labels:
        environment: production
