apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-service
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: LOG_LEVEL
              value: DEBUG
