apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: preview
  name: person-service
spec:
  selector:
    matchLabels:
      environment: preview
  template:
    metadata:
      labels:
        environment: preview
    spec:
      containers:
        - name: app
          env:
            - name: LOG_LEVEL
              value: DEBUG
