---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: person-service
  name: person-service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: person-service
  template:
    metadata:
      labels:
        app: person-service
    spec:
      containers:
        - name: app
          image: ghcr.io/gitops-ci-cd/person-service:5321defb239e7c1e0fb8b79f2274b9b754f05a03
          env:
            - name: PORT
              value: "50051"
          ports:
            - name: grpc
              containerPort: 50051
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 200m
              memory: 200M
