---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: person-service
  name: person-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-service
  template:
    metadata:
      labels:
        app: person-service
    spec:
      containers:
        - name: app
          image: ghcr.io/gitops-ci-cd/person-service:10badc534de66c1c1c5dc189c8117e7c1405f59e
          env:
            - name: PORT
              value: "50051"
          ports:
            - name: grpc
              containerPort: 50051
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 200m
              memory: 200M
